name: "AgentProbe — Adversarial Security Testing"
description: "Run adversarial security tests against your AI agent in CI"
author: "Alexandre Melges"

inputs:
  config:
    description: "Path to agentprobe.yaml config file"
    required: false
    default: "agentprobe.yaml"
  attacks:
    description: "Comma-separated attack suites to run"
    required: false
  severity:
    description: "Minimum severity to report (low, medium, high, critical)"
    required: false
    default: "low"
  format:
    description: "Output format (text, json, markdown)"
    required: false
    default: "text"
  timeout:
    description: "Per-attack timeout in milliseconds"
    required: false
    default: "30000"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install AgentProbe
      shell: bash
      run: npm install -g agentprobe@latest

    - name: Run AgentProbe
      shell: bash
      run: |
        agentprobe \
          --config "${{ inputs.config }}" \
          --severity "${{ inputs.severity }}" \
          --format "${{ inputs.format }}" \
          --timeout "${{ inputs.timeout }}" \
          ${{ inputs.attacks && format('--attacks "{0}"', inputs.attacks) || '' }}
